name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
    
    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '16.x'
    
    - name: Install frontend dependencies and build
      run: |
        cd frontend
        npm ci
        npm run build
    
    # Exemplo de deploy para servidor via SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/nutri-app
          git pull
          cd backend
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart nutri-app-backend
          cd ../frontend
          cp -r /tmp/build/* ./build/
          systemctl restart nginx
